[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "示例站点"
weight = 1

# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 2

